estudiante:
  columns:
    - "estudiante_ingresos"
    - "estudiante_activos"
    - "estudiante_de_grado"
    - "estudiante_de_posgrado"
  names:
    - "Al ingreso"
    - "Estudiantes"
    - "Grado"
    - "Posgrado"
  icons:
    - "ico-mujer.svg"
    - "ico-mujer.svg"
    - "ico-mujer.svg"
    - "ico-mujer.svg"
funcionarie:
  columns:
    - "funcionarie_escalafon_A"
    - "funcionarie_escalafon_B"
    - "funcionarie_escalafon_C"
    - "funcionarie_escalafon_D"
    - "funcionarie_escalafon_E"
    - "funcionarie_escalafon_F"
    - "funcionarie_escalafon_Q"
    - "funcionarie_escalafon_R"
  names:
    - "Escalafon A"
    - "Escalafon B"
    - "Escalafon C"
    - "Escalafon D"
    - "Escalafon E"
    - "Escalafon F"
    - "Escalafon Q"
    - "Escalafon R"
  icons:
    - "ico-mujer.svg"
    - "ico-mujer.svg"
    - "ico-mujer.svg"
    - "ico-mujer.svg"
    - "ico-mujer.svg"
    - "ico-mujer.svg"
    - "ico-mujer.svg"
    - "ico-mujer.svg"
docente:
  columns:
    - "docente_grado_1"
    - "docente_grado_2"
    - "docente_grado_3"
    - "docente_grado_4"
    - "docente_grado_5"
  names:
    - "Grado 1"
    - "Grado 2"
    - "Grado 3"
    - "Grado 4"
    - "Grado 5"
  icons:
    - "ico-mujer.svg"
    - "ico-mujer.svg"
    - "ico-mujer.svg"
    - "ico-mujer.svg"
    - "ico-mujer.svg"
places:
  columns:
    - "hall"
    - "nil"
    - "salones-comunes"
    - "salon-de-actos"
    - "biblioteca"
    - "aula-magna"
    - "otro-especificar"
    - "edificio"
    - "sala-de-reuniones"
  names:
    - "Hall"
    - "Sin especificar"
    - "Salones Comunes"
    - "Salón de actos"
    - "Biblioteca"
    - "Aula Magna"
    - "Otro"
    - "Edificio"
    - "Sala de Reuniones"
  icons:
    - "ico-mujer.svg"
    - "ico-mujer.svg"
    - "ico-mujer.svg"
    - "ico-mujer.svg"
    - "ico-mujer.svg"
    - "ico-mujer.svg"
    - "ico-mujer.svg"
    - "ico-mujer.svg"
    - "ico-mujer.svg"
